# Common development commands. Extra arguments are passed literally to Go/Godog.
set positional-arguments

# List available recipes without changing files.
default:
    @just --list

# Show available recipes.
help:
    @just --list

# Build the CLI into the ignored artifacts directory.
build:
    mkdir -p _artifacts
    go build -o _artifacts/godog ./cmd/godog

# Format Go files, including the examples module.
fmt:
    gofmt -w .

# Check formatting without changing files.
fmt-check:
    @output="$(gofmt -l .)" || exit "$?"; if [ -n "$output" ]; then printf '%s\n' "$output"; exit 1; fi

# Vet both modules.
vet:
    go vet ./...
    cd _examples && go vet ./...

# Run root-module tests with race detection (e.g. just test -run TestName).
test *args:
    go test -race "$@" ./...

# Run the separate examples-module tests with race detection.
test-examples *args:
    cd _examples && go test -race "$@" ./...

# Run strict Godog feature tests (e.g. just bdd --tags=@smoke).
bdd *args:
    go run ./cmd/godog -f progress --strict "$@"

# Run the source CLI (e.g. just godog workflow plan path/to/workflow.yaml).
godog *args:
    go run ./cmd/godog "$@"

# Write root-module coverage into the ignored artifacts directory.
coverage *args:
    mkdir -p _artifacts
    go test -race -covermode=atomic -coverprofile=_artifacts/coverage.txt "$@" ./...

# Open the coverage report generated by `just coverage`.
coverage-html:
    go tool cover -html=_artifacts/coverage.txt

# Check formatting, vet, both test modules, and strict feature tests.
check: fmt-check vet test test-examples bdd
